<?php include('../config/config.php') ?>
<?php $title = 'Report sida';?>
<?php include('../view/header.php') ?>
<div class="two-col-layout-left">
    <main class="main">
        <article class ="article">
            <h1>Redovisning</h1>

           


            <h2 id="kmom01">kmom01</h2>

            <p style="word-spacing: 3px; color: #333"> Hej detta är min första redovisning om kmom01 på webtec kursen! <br>
            Jag började uppgiften igenom att installera labbmiljön förra veckan, det var redan där mycket att lära sig och små och stora problem att ta sig igenom jag fick lära mig hur jag inspekterar vilken version av windows som jag har installerat vilket var windows10p 21h1 det var över kraven iaf så jag kunde fortsätta utan några problem.<br> Jag hade redan VSC sedan innan installerat, men jag har inte använt det sedan jag testat det för ett tag sedan så fick updatera versionen och sedan installerade jag lite bra att ha extensions<br> men att öppna upp VSC igenom WSl/Ubuntu terminalen var en annan femma och fick redan där en massa problem men efter mycket googlande så lyckades jag få fram en lösning till mina besvär.<br> När det gäller XAMMP så var det inga problem jag hade självt användt WAMP tidigare så jag förstog redan lite om hur programmet funkar och används och att byta port och sådant var enkelt och funkade utan några besvär och så var jag i största del klar med att installera in labbmiljön för kursen.<br> När jag skulle installera saker igenom ubuntu så fick jag lite problem men det löste sig genom att skriva sudo för det mesta trotts att jag inte har några färdigheter inom ubuntu och sådant sedan tidigare så gick det hyggligt bra just nu.<br><br>
            Efter att jag tagit del av en del informationen på kmom01 så startade jag med övningsuppgiften och det flöt på rätt så bra tills php koden kom upp, där blev jag lite förvirrad i hur man skulle använda include() funktionen och till att börja så tog jag väck min header och footer på me.php för att ersätta dem med php include men fick sedan en massa errors och byggde tillbaka me.php som den såg ut innan men det visade sig göra minst lika mycke problem när jag körde unicorn, det var inte föränn jag såg på din redovisning i tisdags som jag bestämmde mig för att byta tillbaka till den originella me sidan som jag hadde som var byggd med include, jag var väldigt glad när jag såg dig gå igenom just den delen som jag suttit och klurat på i flera dagar och drog slutsattsen att det finns vissa nackdelar med att börja arbeta tidigt även om resurserna som finns på dbwebb är väldigt bra.<br><br>
            Genom att bygga report sidan så fick jag lära mig väldigt mycket om html,css och php det var saker som jag hade lekt lite med förrut men inget som jag hade någon redig vetskap om sen tidigare men efter uppgiften kan jag iaf säga att jag en väldigt grundläggande förståelse för hur man kan bygga en simpel sida med vissa funktioner.<br> När jag väl kom in i slutuppgiften så fick jag massa frågetecken och hade speciellt problem med att lista ur hur jag skulle ändra färgen på veckan och började nästan direkt att försöka lösa det på svåraste sätt möjligt (enligt mig), jag försökte med internet resurser göra att veckodagen skulle visas upp i en regnbågs färg som updaterades konstant igenom php kod, kan bara skratta lite åt mig själv här för jag kom på efter några timmars försök att det var lite utanför min viktklass när jag knappt kunde förstå vad sakerna i texten gjorde. Då försökte jag istället använda enkel CSS och det var ju betydligt lättare att göra bara en enkel färgändring, jag körde ett inline css på just den veckodagen för att få det som jag ville och med den kunskap som jag har så är jag rätt nöjd men jag är säker på att det kommer finnas ännu bättre lösningar på detta framöver.<br><br>
            Min TIL vore väl att jag lärt mig allting ovanför det var en fasligt massa grejer för en nybörjare som mig men jag fann det väldigt roligt att arbeta med så det var aldrig svårt att komma igång och börja jobba. Kollade lite frammåt och såg att vi skulle ha mkt CSS i nästa moment så jag är rätt så taggad för det var speciellt roligt att hålla på med för mig!


            <h2 id="kmom02">kmom02</h2>

            <p>Det var rätt roligt men jag kom på rätt snabbt att jag gick för långt med färger och sådant och det såg bara konstigt ut, så drog tillbaka
                lite på färgerna och det blev nog lite bättre iaf men kan inte säga att jag någon artistisk kännsla.</p>
                <p> Jag körde lite ljusblått på headern och a hovern samt bylinen, jag gilalde den gråa gradienten på footen så valde samma på nav baren.</p>
                <p>Det var rätt svårt att bestämma sig för vilka färger man ska ha och sedan lägga ihop det för att få en sida som man är nöjd med. Hade själv rätt
                    svårt att förstå hur man kunde ändra t.ex. paragrafer i bara .author eller .article men förstod mig mer på sådant ju längre in jag kom i upgifterna.
                    Jag hade även en h1 i min header/banner grej som gjorde att det blev liksom ett litet vitt område på toppen av skärmen som tog mig en massa tid
                    att klura ut vart det kom ifrån.</p>
                    <p>Det finns en massor med element att lära sig trotts att css är rätt simplistiskt och det handlar mycket om hur du använder dem olika redskapen man har för att göra en snygg webbsida så det är svårt till en början och mycket att gå in på w3schools för att kolla att sakerna blivit rätt och hur man använder nya stylesheets och sådant, men när man har mer erfarenhet så blir det nog rätt enkelt skulle ja tro.
                <p>Jag jag blev väl rätt så nöjd tillslut men det var också en massa grejer som jag skulle vilja ändra men som jag bara inte visste hur man skulle göra,
                    jag ville till exempel ändra bodyn på today sidan men fick bara massa problem och just nu så känns den ju rätt tom så skulle vilja ha lite mer grejor på sidorna
                    så man fyller upp hemsidan lite, skulle vara nice om man kunde göra en navbar som följer med när jag skrollar ner så jag inte måste skrolla up igen om jag vill byta sida (inte direkt med css att göra men vore nice xd) gjorde en enkel to the top knapp för att bespara mitt skroll finger temporärt lol.
                <p> TIL: Mycket om de olika stylarna man kunnde göra i css som t.ex. float, center, rotera, gradient lite om flexbox och hur man kan göra för att ge en speciel style till allt under en del liksom. Men speciellt har jag lärt
                    mig hur svårt det kan vara att designa en snygg hemsida.</p>

                <h2 id="kmom03">kmom03</h2>
                <p> Min uppfattning av PHP hittills är att det är rätt kneppigt om man gemför det med python om man tänker syntax och sådant så är python väldigt snäll emot en och en det finns
                    programm som thonny som är visuall debugger. Med PHP däremot så är det bara att köra in det i hemmsidan som jag förstått det man får ju endå error meddelande på hemmsidan så det hjälper ju
                    men man kan inte gå igenom det så steg för steg som man gör enkelt när man debuggar med thonny, men det finns även bra grejer med PHP som att det värkade vara enkelt att använda tillsammans med html och css.
                    <p> Det känns rätt bra med sidovyer och sidokontrollerna att ha dem uppdelade gör det hela mycket enklare när vi vill ha ett element på sidan så kan vi bara ladda in det som en "funktion" typ och det är smidigt att slippa skriva om kod för varje sidovy.</p>
                    <p> Jag är rätt bekväm med loopar, variabler if satser för att vi användt det i python redan. Det var jobbigare med GET och Querysträngar osv även nu tror jag inte jag har en jätte bra förståelse för hur de funkar men något grundläggande förstår jag. </p>
                    <p> Jag jobbade igenom övningarna och skummade igenom genomgångs videorna på youtube sedan så började jag med fredags sidan jag copypasta in mina vyer configs osv och sedan anände jag date('N') för att få nummer på dagarna
                        när värdet var 5 så öppnade jag dem "gömda" gifsen och m4pan annars visades "days till friday" fick lite problem med lördag söndag så satt in två if satser som återgärdade problemet. Jag blev rätt nöjd men jag får stora problem med att få css layouten att se ut som jag vill.</p>
                    <p> Jag skriver först en massa variabler som har ett värde som ges av GET strular rätt mycket med att få allt att funka och sedan skriver börjar jag min for loop för totala mängden dagar i månaden
                        när $i == 1 så skrev jag ut veckan if satser för måndag söndag för veckan/röda dagar och elseif det inte är mån/sön körs tablen som vanligt, jag hade störst problem med att fårstå hur jag skulle tilldela klass till td tr inom phpn men kom på sen att jag bara skulle ta väck "" så funkade det utan större problem.</p>
                    <p> TIL; Jag lärde mig uppskatta thonny debbugern väldigt mycket lärde mig även återigen att css vill aldrig som jag vill samt lärde jag mig lite om hur syntax och sådant ser ut i PHP och hur man använder dem inbyggda funktionerna som date.</p>


                    <h2 id="kmom04">kmom04</h2>
                    <p>Det känndes okay-ish, det var lite jobbigt till att börja med mest för att jag hade svårt att förstå vad alla nya begreppen var som key value name etc men det gick väl bra och jag lärde mig något för nästa moment i python till och med. </p>
                    <p>Funktioner har vi i webprogrammering arbetat rätt mycket med redan i python kursen så det känndes rätt normalt att börja använda det här också men fick ändå några svårigheter med hur jag skulle använda dem med keys osv på typ gissnings leken.</p>
                    <p>När man använder GET så synns det uppe i sökfältet man skapar liksom en ny sida på sidan med ett redigerat datum som jag förstår det? lite osäker. POST är ett formulär där du kan skicka in detaljer sedan kan du även se om allting är ifyllt i formuläret med php samt redirecta till en annan sida baserat på resultatet inte helt hundra på exakt allt vad detta kan användas för just nu men det värkar just smidigt för formulär eller typ opinionsbildning. </p>
                    <p>Det gick okej att arbeta med Session lite klurigt i början som vanligt men det gick på rätt mycket snabbare än mycket annat i detta momentet. Det var rätt kul att arbeta med och lärde mig hur man kunde flytta över variablar från sida till sida med session vilket säkert kommer vara användbart framöver också.</p>
                    <p>Jag slog mitt huvud mot tangentbord i ungefär 1 och en halv vecka tills jag förstog hur man kunde lösa uppgifterna jag hade nog kunnat arbeta snabbar om jag hade skräpat allt det jag gjort i förra momentet (kalender delen) och bara arbetat helt från scratch med dem nya sakerna vi lärde oss här men jag fick i alla fall den nya almenacken att fungera det tog bara lite längre tid än jag hade velat men jag är nöjd med resultatet.</p>
                    <p>Uppgiften med guessname leken hade jag nog enbart svårt med att förstå hur jag skulle få ut andra värdet med nyckel men efter jag fick hjälp med den delen av en klasskamrat så gick det snabbt att göra klart </p>
                    <p>Att man ska ta sin tid på alla momenten och göra det i bra ordning istället för att bara försöka tvinga sakar att fungera.</p>

                    <h2 id="kmom05">kmom05</h2>
                    <p>Det var hygligt lätt att förstå sig på efter genomgången och känndes bra att jobba med. Jag hade inga tidigare förkunskaper kring sånt här men det verkade inte vara jätte krångligt, i alla fall inte med den nivå som vi håller på med just nu.</p>
                    <p>Nej det var enkelt jag följde efter genomgången medans jag gjorde det så hade jag några frågor så blev dem oftast besvarade rätt snabbt.</p>
                    <p>Inte direkt det var typ samma som övning 1 vi använde ju mycket saker vi jobbar med tidigare typ jag ser sql grejen som typ en funktion som är redigt bra och lätt att använda om man vill tex söka igenom en databas du kan köra efter många olika kriterier som perfekt matchning eller partial match m.m säkerligen den känns rätt flexibel.
</p><p> Jag började med att ta grunden av det jag hade gjort i övningarna och sedan byggde jag på det för att möta kraven som uppgifterna hade. På uppgift 1 så körde jag igenom två databaser för att få ut både namn id namnsdag samt namn beskrivningen och det var enkelt och smidigt var det något jag hade svårt med så var det nog att fixa href och utskrivt om det inte fanns någon namn beskrivelse på samma rad som beskrivning hade funnits men det tog inte så lång tid endå</p>
<p> På övning två så strulades de lite men gick bra sedan jag skulle bara se till så att jag hade med datan in till andra sidan så jag inte fick några fel utskrifter, jag tror jag hade mer problem med css och filsökvägen, i denna övningen än något annat för filsökvägen förändras då denna map inte ligger direkt under public som förstörde rätt mycket saker om jag bara skulle includa navbaren t.ex. sen så vill footern bara inte med och ser ut som en fet fyrkant utan förklarbar anledning trots att jag har samma css ref på alla sidokontroller, jag hade samma problem med sökfältet på en av övningarna men jag förstår inte hur jag kan fixa det efter timmar av googling.</p>
<p>SQL,SQLite är rätt enkelt att använda efter bara en liten stund och kan göra saker rätt effektivt och det är gratis så jag förstår varför det har så många användar, det känndes smidigt och effektivt jag fick lite problem men det var för de mesta enkelt att klura ut. TIL kan väl då vara att SQL är en helt okej grej att arbeta med.</p>
                    <h2 id="kmom06">kmom06</h2>
                    <p>Det var rätt kul att jobba med SQL med konceptet Create, read, update och delete det känndes effektivt och ett bra sätt att slippa göra om massa kod genom att bara ha sql filerna stå för sakerna vi ville skapa i övningen antagligen så har väl ni gjort sql "funktionerna" eller vad jag nu ska kalla de men det borde även vara ett enkelt sätt att jobba med när vi behöver göra sakerna själva istället för att använda sql sakerna som redan ni hade gjort. Men ja crud konceptet var kul och så det är liksom byggstenarna för en databas kanske att kunna updatera lägga till ta bort och så vidare.</p>
                    <p>Jag jobbade på med inloggning och det var rätt enkelt att använda och förstå i stor del men det med hash lösenord kryptering och sånt kan jag inte säga att jag förstog mycket av hur det funkade. Men det var bara att kolla så att användaren matchade ett akronym lösenord kombination i databas filen. Sedan skulle vi gjöra så man kunde skapa ett konto så det gjorde vi med create gjorde ett formulär med användarnamn och lösenord och så nöjde vi oss med det och låter användaren ändra det i en av de senare delarna med UPDATE. Sen skulle vi kunna DELETa användaren som vi precis skapat så då gjorde vi något som kunde göra det. Det var mycket återanvändning av samma kod vilket gjorde allting väldigt snabbt att göra bara att ändra några radar liksom och vi hålde samma struktur på alla sidorna vi gjorde i övningen liksom något.php som main sida med vyer includade eller requierade sedan en view/något.php sida med formulär och procces.php som processade det vi fått från formuläret. Vi rörde vid alla momenten i CRUD genom delarna av övningen på ett enkelt och strukturerat sätt så det gick bra och lätt som de flesta momenten i webtec väldigt bra strukturerat med lärorika övningar som är direkt linkade med slut uppgiften på momentet.</p>
                    <p>Blev rätt nöjd med min kod men har fortfarande stora problem med css, den vill inte som jag vill. Min footer är besatt av att lägga sig i mitten av sidan och jag förstår bara inte varför. Min me/report är helt fylld av dem tidigare momenten och det har börjat bli lite jobbigt att hitta sig fram i VSC då det är så många filer nu, så jag hade nog velat strukurera mina mappar lite bättre i framtiden, jag flyttade runt med det lite detta momentet men fortfarnde rätt mycket kvar även efter jag städat.</p>
                    <p>Lärde mig lite om CRUD och att arbeta med databas filer, det var rätt kul och intressant. </p>

                    <h2 id="kmom10">kmom10</h2>
                    
                    <p>Så jag började projektet med att använda det som vi gjort tidigare som grund och sen byggde jag steg efter steg upp en ny hemsida med annorlunda utseende, jag använde cssn vi lärt oss tidigare för att göra vad jag tyckte var snyggt för hemmsidan och sedan började jag att arbeta med Objekt sidan.</p>
                    <p>För att ladde in objekten ariklarna och sådant så använde jag databasen för tabbelerna så använde jag for each $row för att få in allting.</p>
                    <p>För dem individuella sidorna på artikel och objekt så använde jag "select name, * from object where name = '$stuff';" där stuff är "$stuff = $_GET['page'] ?? "";" för att bara läsa in dem individuella sidorna.</p>
                    <p>På Objekt.php så skulle jag klura ut ett sätt att bygga upp hemsidan med pdo så jag använde mig av en tabell likt det vi gjort i tidigare moment i kursen så jag ladde upp 3 specifika saker jag ville ha vilket var namnet på objektet en Image och ett kort stycke som beskrev objektet.</p>
                    <p>Jag gjorde en href av namnet på objektet vilket laddade in det specifika objektets sida med pdo likt det jag gjorde för tabellen men här endast för detta objektet, sen så började jag jobba på att göra så man kunnde gå previous page och next page och fixade det genom att göra ett "shift" på valuet så det blev korrekt iom att du gjorde så att alla värderna var skumma typ började på 3 och så, jag klurade på det lite men det funkade sen och då gick jag vidare till att göra Artikel sidan. </p>
                    <p>När jag började jobba med Artikel sidan så tog jag det som jag gjort för Objekt i grund och sedan bytte ut dem saker jag ville ladde in på Articles jag valde att läsa in Objekt namnen och sedan en andra spalt för författarens namn, jag använde även här en href på objektets namn för att linka till en pdo laddad sida med get för att bestämma vilken artikel/objekt som laddades in likt det jag gjort på objekt.</p>
                    <p>Det gick lika enkelt att fixa dem specifika sidorna för artikel för det var ungefär samma som för Objekt men när jag skulle börja med krav4 på Artiklar så blev det en massor med problem då värderna på dem olika Artiklarna var helt måfå så kunde jag inte använda samma teknik som jag hade gjort för Objekten och var tvungen att hitta på något nytt. Efter jag klurat en stund så kom jag på att jag skulle göra en variabel för nyckeln eller id eller vad jag ska säga, typ $res['$pagenum']['id'] och jag fick en kortvarig vinst där men jag förstår inte varför den ville hopppa två steg och ibland skickade sida 5 dig till typ sida 11 och jag lyckades inte lösa det och var tvungen att ge upp jag är redan sen som det är och måste börja med dem nya kurserna</p>
                    <p>Jag kollade även in på krav 5 lite snabbt med Galleri men det var jobbigare än jag trodde och var även där tvungen att ge upp bara några timamr in, jag tänkte jag gör en knapp som skickade dig till de nästa 5 men då tömdes min variabel från när jag hade skrivit in hur många variablar jag ville ha och det blev massor med problem.</p>
                    <p>Krav 6 gjorde jag inte om jag hade gjort det hade jag kunant redigera och göra krav 4 mycket enklare dock så det är rätt intressant.</p>
                    <h2>2.</h2>
                    <p>Krav 1-3 gick relativt snabbt och det inget nytt redigt men jag strulade som sagt en del med övriga krav, projektet skulle jag säga var lagom svårt hade jag användt min tid bättre tror jag att jag iaf hade klarat av att göra något krav mer så jag skulle inte säga att det är jätte svårt men endå så är det rätt klurigt.Jag tyckte det var rätt rimligt projekt för kursen.Jag hade lite svårt att visualisera för hur hemsidan skulle se ut då nvm sidan låg nere men jag försökte tyda mig fram och hoppas att min hemsidas utseende ser ut som den ska.</p>
                    <h2>3.</h2>
                    <p>Jag tyckte att materialet vi fick var mycket lärosamt och bra för att förklara övningarna och uppgifterna, videorna var bra upplaggda och enkla att följa efter under lektionerna om man ville göra det.Jag är rätt nöjg med kursen lite mindre med mitt eget utförande av projektet hade nog velat göra allt men jag har provat allt jag vet även gott tilbaka utan att hitta bra svar för att lösa uppgifterna.Jag hade givit kursen en solid 9/10 men jag vet inte om jag missat något men slutprojektet känndes som en står step up i svårighetsgrad och det var rätt mycket nytt på projektet som vi var tvungna att fylla i själva, det är i och för sig inte något fel med det, men det känndes som att jag hade missat något viktigt som jag inte kunnde hitta i tidigare kurs moment.</p>
                    <p>Tack för denna kursen i alla fall det var både lärorikt och roligt på många sätt</p>
                    
            <?php include('../view/byline.php') ?>

        </article>
    </main>
    <aside class="aside-left">
        <h1> Innehållsförteckning</h1>
        <ul>
                <li><a href="#kmom01">kmom01</a></li>
                <li><a href="#kmom02">kmom02</a></li>
                <li><a href="#kmom03">kmom03</a></li>
                <li><a href="#kmom04">kmom04</a></li>
                <li><a href="#kmom05">kmom05</a></li>
                <li><a href="#kmom06">kmom06</a></li>
                <li><a href="#kmom10">kmom10</a></li>
            </ul>
        <hr>
        
        <p> innehåll här och sådant </p>
        <hr>
    </aside>
</div>

<?php include('../view/footer.php') ?>

<!-- Windows10P 21H1,VSC,WSL/Ubuntu,XAMPP<br><br>Det krånglade rätt mycket men jag tror att jag har lyckats få rätt på det<br><br>Något men inte speciellt mycket kunskap om terminalen visste hur man fick fram den men det är nog allt.<br><br>Väldigt ytlig kunskap om vad det är och vad det används för men ingen speciell kunskap om hur jag använder det.<br><br>Det gick inte väldigt bra, jag spendarde mest tid bara för att hitta teknikerna för det jag ville göra på hemmsidan och sedan resterande för att försöka hemma alla errors och saker som dykt upp när jag körde Unicorn, men jag har kämpat mig igenom det.<br><br>TIL att det finns en massa grejer man göra med css och php även om jag inte kan använda skickligt ännu.</p> -->